//! # Trivela Campaign Contract
//!
//! On-chain campaign metadata and eligibility for Trivela.
//! Stores campaign config and allows checking participant status.
//!
//! ## Merkle allowlist
//!
//! When a Merkle root is set via `set_merkle_root`, all calls to `register`
//! must include both a `leaf` (the 32-byte value committed in the tree) and
//! a valid sibling-hash `proof`.
//!
//! ### Leaf convention
//! Off-chain tooling must build the tree with
//! `leaf = sha256(address_xdr_bytes)` for each allowlisted address, and pass
//! that pre-computed leaf on-chain.  Pairs are hashed in sorted order so
//! proofs are position-independent (the same convention as OpenZeppelin's
//! `MerkleProof`).
//!
//! ### Security note
//! `participant.require_auth()` ensures only the participant's own keypair
//! can submit a registration transaction, so a third party cannot register
//! an address on someone's behalf.  The expected leaf for a given address
//! should be generated by a trusted off-chain tool so that only genuinely
//! allowlisted addresses possess a valid `(leaf, proof)` pair.

#![no_std]

use soroban_sdk::{
    contract, contracterror, contractimpl, contractmeta, symbol_short, Address, Bytes, BytesN, Env,
    Symbol, Vec,
};

#[contracterror]
#[derive(Clone, Copy, Debug, Eq, PartialEq, PartialOrd, Ord)]
#[repr(u32)]
pub enum Error {
    Unauthorized = 100,
    OutsideTimeWindow = 101,
    CapacityReached = 102,
    CampaignInactive = 103,
    NotInAllowlist = 104,
    UnsupportedMigration = 105,
}

contractmeta!(key = "Description", val = "Trivela campaign configuration");

const ADMIN: Symbol = symbol_short!("admin");
const CAMPAIGN_ACTIVE: Symbol = symbol_short!("active");
const PARTICIPANT: Symbol = symbol_short!("partic");
const START_TIME: Symbol = symbol_short!("start");
const END_TIME: Symbol = symbol_short!("end");
const MAX_CAP: Symbol = symbol_short!("maxcap");
const PARTICIPANT_COUNT: Symbol = symbol_short!("count");
const MERKLE_ROOT: Symbol = symbol_short!("mkroot");
const SCHEMA_VERSION: Symbol = symbol_short!("schema_v");
const CURRENT_SCHEMA_VERSION: u32 = 1;

#[contract]
pub struct CampaignContract;

/// Hash two 32-byte values in sorted order so proofs are position-independent.
fn hash_pair(env: &Env, a: BytesN<32>, b: BytesN<32>) -> BytesN<32> {
    let (left, right) = if a <= b { (a, b) } else { (b, a) };
    let mut combined = [0u8; 64];
    combined[..32].copy_from_slice(&left.to_array());
    combined[32..].copy_from_slice(&right.to_array());
    env.crypto()
        .sha256(&Bytes::from_slice(env, &combined))
        .into()
}

/// Verify that `leaf` is included in the tree identified by `root` using the
/// given sibling-hash `proof`.
fn verify_merkle_proof(
    env: &Env,
    leaf: BytesN<32>,
    proof: &Vec<BytesN<32>>,
    root: &BytesN<32>,
) -> bool {
    let mut computed = leaf;
    for sibling in proof.iter() {
        computed = hash_pair(env, computed, sibling);
    }
    &computed == root
}

#[contractimpl]
impl CampaignContract {
    /// Initialize campaign contract with an admin.
    pub fn initialize(env: Env, admin: Address) -> Result<(), Error> {
        env.storage().instance().set(&ADMIN, &admin);
        env.storage().instance().set(&CAMPAIGN_ACTIVE, &true);
        env.storage().instance().set(&START_TIME, &0u64);
        env.storage().instance().set(&END_TIME, &u64::MAX);
        env.storage().instance().set(&PARTICIPANT_COUNT, &0u64);
        env.storage()
            .instance()
            .set(&SCHEMA_VERSION, &CURRENT_SCHEMA_VERSION);
        env.storage().instance().extend_ttl(50, 100);
        Ok(())
    }

    /// Returns the active storage schema version for this contract.
    pub fn schema_version(env: Env) -> u32 {
        env.storage()
            .instance()
            .get(&SCHEMA_VERSION)
            .unwrap_or(CURRENT_SCHEMA_VERSION)
    }

    /// Migration entrypoint for future schema transitions.
    ///
    /// For now, version `1` is the only supported schema and this function
    /// serves as an idempotent migration hook for upgrade workflows.
    pub fn migrate(env: Env, admin: Address, target_version: u32) -> Result<u32, Error> {
        admin.require_auth();
        let stored: Address = env.storage().instance().get(&ADMIN).unwrap();
        if stored != admin {
            return Err(Error::Unauthorized);
        }
        if target_version != CURRENT_SCHEMA_VERSION {
            return Err(Error::UnsupportedMigration);
        }
        env.storage()
            .instance()
            .set(&SCHEMA_VERSION, &CURRENT_SCHEMA_VERSION);
        env.storage().instance().extend_ttl(50, 100);
        Ok(CURRENT_SCHEMA_VERSION)
    }

    /// Set registration time window (admin only).
    pub fn set_window(env: Env, admin: Address, start: u64, end: u64) -> Result<(), Error> {
        admin.require_auth();
        let stored: Address = env.storage().instance().get(&ADMIN).unwrap();
        if stored != admin {
            return Err(Error::Unauthorized);
        }
        env.storage().instance().set(&START_TIME, &start);
        env.storage().instance().set(&END_TIME, &end);
        env.storage().instance().extend_ttl(50, 100);
        Ok(())
    }

    /// Set campaign active flag (admin only).
    pub fn set_active(env: Env, admin: Address, active: bool) -> Result<(), Error> {
        admin.require_auth();
        let stored: Address = env.storage().instance().get(&ADMIN).unwrap();
        if stored != admin {
            return Err(Error::Unauthorized);
        }
        env.storage().instance().set(&CAMPAIGN_ACTIVE, &active);
        env.storage().instance().extend_ttl(50, 100);
        Ok(())
    }

    /// Set maximum participant cap (admin only). Set to 0 for unlimited.
    pub fn set_max_cap(env: Env, admin: Address, max_cap: u64) -> Result<(), Error> {
        admin.require_auth();
        let stored: Address = env.storage().instance().get(&ADMIN).unwrap();
        if stored != admin {
            return Err(Error::Unauthorized);
        }
        env.storage().instance().set(&MAX_CAP, &max_cap);
        env.storage().instance().extend_ttl(50, 100);
        Ok(())
    }

    /// Set the Merkle root for allowlist-gated registration (admin only).
    ///
    /// Once set, every `register` call must supply a valid `(leaf, proof)`.
    /// Remove the root by calling this again with a root of all zeros to
    /// revert to open registration.
    pub fn set_merkle_root(env: Env, admin: Address, root: BytesN<32>) -> Result<(), Error> {
        admin.require_auth();
        let stored: Address = env.storage().instance().get(&ADMIN).unwrap();
        if stored != admin {
            return Err(Error::Unauthorized);
        }
        env.storage().instance().set(&MERKLE_ROOT, &root);
        env.storage().instance().extend_ttl(50, 100);
        Ok(())
    }

    /// Return the current Merkle root, or `None` when open registration is active.
    pub fn get_merkle_root(env: Env) -> Option<BytesN<32>> {
        env.storage().instance().get(&MERKLE_ROOT)
    }

    /// Register a participant.
    ///
    /// `leaf`  – the 32-byte leaf value committed in the Merkle tree for this
    ///           participant.  Must be `sha256(address_xdr_bytes)` for the
    ///           caller's address, computed by off-chain tooling.
    ///
    /// `proof` – ordered list of sibling hashes for the Merkle path from
    ///           `leaf` to the stored root.  Pass an empty `Vec` when no root
    ///           is configured.
    ///
    /// Returns `true` on first registration, `false` if already registered.
    pub fn register(
        env: Env,
        participant: Address,
        leaf: BytesN<32>,
        proof: Vec<BytesN<32>>,
    ) -> Result<bool, Error> {
        participant.require_auth();

        let active: bool = env
            .storage()
            .instance()
            .get(&CAMPAIGN_ACTIVE)
            .unwrap_or(false);
        if !active {
            return Err(Error::CampaignInactive);
        }

        let now = env.ledger().timestamp();
        let start: u64 = env.storage().instance().get(&START_TIME).unwrap_or(0);
        let end: u64 = env.storage().instance().get(&END_TIME).unwrap_or(u64::MAX);

        if now < start || now > end {
            return Err(Error::OutsideTimeWindow);
        }

        // Merkle allowlist check – skipped when no root is stored.
        if let Some(root) = env
            .storage()
            .instance()
            .get::<_, BytesN<32>>(&MERKLE_ROOT)
        {
            if !verify_merkle_proof(&env, leaf, &proof, &root) {
                return Err(Error::NotInAllowlist);
            }
        }

        let key = (PARTICIPANT, participant.clone());
        if env
            .storage()
            .instance()
            .get::<_, bool>(&key)
            .unwrap_or(false)
        {
            return Ok(false);
        }

        let max_cap: u64 = env.storage().instance().get(&MAX_CAP).unwrap_or(0);
        if max_cap > 0 {
            let count: u64 = env
                .storage()
                .instance()
                .get(&PARTICIPANT_COUNT)
                .unwrap_or(0);
            if count >= max_cap {
                return Err(Error::CapacityReached);
            }
        }

        env.storage().instance().set(&key, &true);

        let count: u64 = env
            .storage()
            .instance()
            .get(&PARTICIPANT_COUNT)
            .unwrap_or(0);
        env.storage()
            .instance()
            .set(&PARTICIPANT_COUNT, &(count + 1));

        env.storage().instance().extend_ttl(50, 100);
        Ok(true)
    }

    /// Check if a participant is registered.
    pub fn is_participant(env: Env, participant: Address) -> bool {
        env.storage()
            .instance()
            .get(&(PARTICIPANT, participant))
            .unwrap_or(false)
    }

    /// Check if campaign is active.
    pub fn is_active(env: Env) -> bool {
        env.storage()
            .instance()
            .get(&CAMPAIGN_ACTIVE)
            .unwrap_or(false)
    }

    /// Get current participant count.
    pub fn get_participant_count(env: Env) -> u64 {
        env.storage()
            .instance()
            .get(&PARTICIPANT_COUNT)
            .unwrap_or(0)
    }

    /// Get maximum participant cap (0 means unlimited).
    pub fn get_max_cap(env: Env) -> u64 {
        env.storage().instance().get(&MAX_CAP).unwrap_or(0)
    }
}

#[cfg(test)]
mod test;
